version: '3.2'

networks:
  stark_network:
    driver: bridge

services:

  ##################################################
  ######                MYSQL                #######
  ##################################################

  stark_mysql:
    image: mysql/mysql-server:8.0
    container_name: stark_mysql
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./resources/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Qazxsw123
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: user
      MYSQL_PASSWORD: Qazxsw123
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - stark_network
